### PR TITLE
Refactor logging

### PR DESCRIPTION
**Pull request by surik**
Relate to #13

### CODE REVIEW

**Comment by RoadRunnr** [comment]
Just my 2 cent, feel free to ignore...

lager uses a parse_transform for it's log functions for a good reason, replacing that with a macro is IMHO no a good idea. And maybe_log/2 is not achieving the same effect the parse_transform has.

**Comment by surik** [comment]
@RoadRunnr yes, you right. lager uses parse_transform but in this case I have 2 points:
1) Macro needed for correct line and module definition
2) maybe_log/2 needed for lazy formatting (fmt_response/1, fmt_request/1, etc...)

**Comment by RoadRunnr** [comment]
> 1) Macro needed for correct line and module definition

the parse_transform can easily preserve the line and module definition
 
> 2) maybe_log/2 needed for lazy formatting (fmt_response/1, fmt_request/1, etc...)

yes, you do perform the formatting only when the log level is active, but any function in your log arguments is executed regardless of the log level, the parse_transform does prevent this from happening.

**Comment by surik** [comment]
Let compare 
``` ?LOG_REQUEST(async_reply, [CallbackModule, self(), Request, {ok, Result}]).```
and 
```lager:info([{class, hello}, {hello_request, api}, {hello_handler, CallbackModule}], "async reply on ~p. ~s - ~s",  [HandlerPid, fmt_request(Request), fmt_response(Response)]). ```

1) if I add new trace or change format I will need to replace many places.
2) if I do it in function I will lose line and module
3) if I use ```lager:info``` runtime system will evaluating fmt_reqesut and fmt_response (or am i wrong?)

**Comment by RoadRunnr** [comment]
> 1) if I add new trace or change format I will need to replace many places.

Yes

> 2) if I do it in function I will lose line and module

Yes

> 3) if I use lager:info runtime system will evaluating fmt_reqesut and fmt_response (or am i wrong?)

You are wrong, The lager parse_transform will embedded a piece code that only evaluates the arguments when the log level is enabled. Avoiding the argument evaluation is the exactly the reason for using a parse_transform in the first place.

The code that is inserted is something like this: https://github.com/basho/lager/blob/master/src/lager.erl#L84

The best solutions could be either:
1) use a macro to construct a lager:info/error/warning invocation
2) create a parse_transform that does what lager does plus the needed hello functions

**Comment by surik** [comment]
> You are wrong, The lager parse_transform will embedded a piece code that only evaluates the arguments when the log level is enabled. Avoiding the argument evaluation is the exactly the reason for using a parse_transform in the first place.

My fault. I have looked into AST after parse_transform and understood how it works.
I' going to rework it with your notes

**Comment by surik** [comment]
Done

**Comment by RoadRunnr** [comment]
I like it, @liveforeverx has the final say ;-)

**Pull request merged**
